### ISSUE TITLE
Pipeline on Windows

### ISSUE THREAD

**Issue by p-himik** [nlpub/pymystem3#11]
Can someone please explain why the pipeline mode is disabled on non-POSIX platforms? Enabling it doesn't give me any errors and at least seems to provide a correct output. I can't rigorously check the output for correctness at the moment, but even if I'm wrong, I think it's worthwhile to add some documentation since disabling pipeline makes mystem work on multiple inputs slower by ~3 orders of magnitude.

**Comment by alexanderpanchenko** [comment]
No specific reason for this. You are welcome to propose a pull request where it is enabled!
