### ISSUE TITLE
ResourceWarning raising

### ISSUE THREAD

**Issue by daskol** [nlpub/pymystem3#15]
If one calls `resetwarnings()`, starts mystem and lemmatizes something then python will notify with `ResouceWarning` due to opened IO pipes like following.

```
/lib/python3.6/site-packages/pymystem3/mystem.py:210: ResourceWarning: unclosed file <_io.FileIO name=5 mode='wb' closefd=True>
  self._proc = None
/lib/python3.6/site-packages/pymystem3/mystem.py:210: ResourceWarning: unclosed file <_io.FileIO name=6 mode='rb' closefd=True>
```

**Comment by alexanderpanchenko** [comment]
Thank you for reporting this issue: due to the limited amount of resources, a pull request with a fix is greatly appreciated.

**Comment by daskol** [comment]
Okay. Could you update package on PyPI after fix applying?

**Comment by alexanderpanchenko** [comment]
sure, i will try to update by the end of the week

meanwhile you can pip install git+https://github.com/nlpub/pymystem3

**Comment by alexanderpanchenko** [comment]
uploaded the new version to pypi
https://pypi.python.org/pypi?:action=display&name=pymystem3&version=0.1.6

**Comment by daskol** [comment]
That is great!
