### ISSUE TITLE
No module named 'fcntl' on windows7

### ISSUE THREAD

**Issue by DanteOnline** [nlpub/pymystem3#19]
pip install pymystem3 (python 3.6.2)

`
text = 'мама маму'
m = Mystem()
result = m.lemmatize(text)
`

error No module named 'fcntl'

**Comment by alexanderpanchenko** [comment]
i do not have access to a window box at the moment (and the Travis CI only builds for Linux and Mac OSX). Howver, it seems that the library was used by Windows users (but AFAIK of Windows 8+). Maybe (just a guess) on Windows 8+ this issue is solved somehow...

This is a non-trivial issue to solve: One needs to use Win32 API instead of fcntl sys calls: 
https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows

If you can contribute the solution of this problem implementing for windows the workaround using the native Win32 api calls, such a pull request is highly welcome.

**Comment by peter-pogorelov** [comment]
The same issue. Suppuse that this problem came with a new update, because I can successfuly use the last version of pymystem3 (replaced code of "mystem.py" from last version to older one).

**Comment by alexanderpanchenko** [comment]
can you please write to which exactly older version you replaced the code
of mystem.py?

**Comment by alexanderpanchenko** [comment]
i reverted the change which was seemingly causing the problem (i have no windows box, so cannot test it). can you try to install the new version of the package from pip?

**Comment by peter-pogorelov** [comment]
Thanks! But it would be nice to avoid usage python version-specific libraries too (replace ifilter -> filter, imap -> map). 

`>>> import pymystem3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\LoadAdmin\Desktop\pymystem3-master\pymystem3\__init__.py", line
 12, in <module>
    from .mystem import (Mystem, autoinstall)  # noqa
  File "C:\Users\LoadAdmin\Desktop\pymystem3-master\pymystem3\mystem.py", line 8
, in <module>
    from itertools import ifilter, imap
ImportError: cannot import name 'ifilter'`

Function "unicode" is also supported only in python2.7.
`    _NL = unicode('\n').encode('utf-8')
NameError: name 'unicode' is not defined`

Method "iteritems" of "dict" object was replaced to "items" in python3.
`    for k, v in kvs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'`

And actually I stuck on this error message:
`    if isinstance(url, basestring):
NameError: name 'basestring' is not defined`

PS. Sorry if I do something wrong, I simply cloned master branch and run "pip install ." :)

**Comment by alexanderpanchenko** [comment]
Hello, which windows version you use?

**Comment by peter-pogorelov** [comment]
Win7

**Comment by alexanderpanchenko** [comment]
Can you please write if the same is observed on Windows 8+ or this is Windows 7 specific?

**Comment by eugenso** [comment]
I was able to install pymstem3 on a Windows 10 machine, running a fresh Python 3.6.3 installation. So maybe this is really Win 7 related.

**Comment by alexanderpanchenko** [comment]
Can you also please run the test example from the readme? It is loaded
lazily and the error still may occur on win10.

**Comment by eugenso** [comment]
Seems to work fine, exactly the same output as in the README:
>>> from pymystem3 import Mystem
>>> text = "Красивая мама красиво мыла раму"
>>> m = Mystem()
>>> lemmas = m.lemmatize(text)
>>> print (''.join(lemmas))
красивый мама красиво мыть рама

**Comment by alexanderpanchenko** [comment]
great, thanks. that helps a lot to narrow down the issue.

**Comment by alexanderpanchenko** [comment]
Hello, 

Due to the lack of a Windows 7 machine and the fact that the issue seems to be Windows 7 specific I cannot deliver a fix. You are however welcome to proivde a pull request which fixes the problems on Windows 7. We may have a separate release / branch / package which supports Windows 7.

**Comment by DanteOnline** [comment]
Hello,

Sorry, was busy.
Problem on windows 7.
I can use ubuntu. There works fine.

**Comment by alexanderpanchenko** [comment]
I will close this issue for now.
