### ISSUE TITLE
Pypi upload doesn't match the code at this repository

### ISSUE THREAD

**Issue by uruz** [nlpub/pymystem3#20]
Hello. It turns out that this repo is missing some changes that are made to the same version uploaded to pypi.python.org. One this I have found is python3 compatibility: `unicode` is replaced with `str`. Could you please provide these changes or maybe I am missing out something?

**Comment by alexanderpanchenko** [comment]
i've uploade the latest version which corresponds to https://github.com/nlpub/pymystem3/releases/tag/0.1.10

**Comment by uruz** [comment]
Thank you!
