### ISSUE TITLE
Upgrade Mystem version to 3.1

### ISSUE THREAD

**Issue by Pehat** [nlpub/pymystem3#22]
As far as I can see at https://tech.yandex.ru/mystem/  , there is 3.1 version of Mystem. Please upgrade if possible.

**Comment by alexanderpanchenko** [comment]
Do you know if there are any changes in the interface of the tool or it is
just a matter of binary swap? We have only a very little amount of
resources to maintain this project - help with PR is highly appreciated.

**Comment by alexanderpanchenko** [comment]
if the change is only in the interfaces, it seems to be just a matter of adding new URLs. however, if it is not the case (some interfaces are changed) please let me know.

**Comment by crazyministr** [comment]
@alexanderpanchenko, Yes, there is no interface changes. I can do pull request.
Just one question is what to do with 32bit architectures and freebsd platform ?
I guess we have to leave 3.0 version for it.

**Comment by alexanderpanchenko** [comment]
Yes. That would be great. Let's just suggest using ver. 0.1.10 for those
who need 32 bit support.

**Comment by alexanderpanchenko** [comment]
https://pypi.org/project/pymystem3/0.2.0/
