### ISSUE TITLE
Your system is not supported.

### ISSUE THREAD

**Issue by klementev-v** [nlpub/pymystem3#26]
I tried to launch the sample piece of code to try out pymystem3. 
`from pymystem3 import Mystem`
`text = "Красивая мама красиво мыла раму"`
`m = Mystem()`
`lemmas = m.lemmatize(text)`
`print(''.join(lemmas))`
The module had been installed successfully (version 0.2.0.), but the error is printed:

> NotImplementedError: Your system is not supported. Feel free to report bug or make a pull request.

What's going wrong? How can I fix it?

**Comment by alexanderpanchenko** [comment]
I've just tried to install it on Ubuntu 16.04 / Anaconda 3* and it seems to work fine. What is your system? 

```
(root) panchenko@ltgpu2$ pip install pymystem3
Collecting pymystem3
  Downloading https://files.pythonhosted.org/packages/00/8c/98b43c5822620458704e187a1666616c1e21a846ede8ffda493aabe11207/pymystem3-0.2.0-py3-none-any.whl
Requirement already satisfied: requests in /srv/home/panchenko/anaconda/lib/python3.6/site-packages (from pymystem3) (2.18.4)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /srv/home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /srv/home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /srv/home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /srv/home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (2017.7.27.1)
Installing collected packages: pymystem3
Successfully installed pymystem3-0.2.0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


(root) panchenko@ltgpu2$ ipython
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pymystem3 import Mystem

In [2]: text = "Красивая мама красиво мыла раму"

In [3]: m = Mystem()
   ...: lemmas = m.lemmatize(text)
   ...: print(''.join(lemmas))
   ...:
Installing mystem to /srv/home/panchenko/.local/bin/mystem from http://download.cdn.yandex.net/mystem/mystem-3.1-linux-64bit.tar.gz
красивый мама красиво мыть рама

```

**Comment by klementev-v** [comment]
> I've just tried to install it on Ubuntu 16.04 / Anaconda 3* and it seems to work fine. What is your system?
> 
> ```
> (root) panchenko@ltgpu2$ pip install pymystem3
> Collecting pymystem3
>   Downloading https://files.pythonhosted.org/packages/00/8c/98b43c5822620458704e187a1666616c1e21a846ede8ffda493aabe11207/pymystem3-0.2.0-py3-none-any.whl
> Requirement already satisfied: requests in /srv/home/panchenko/anaconda/lib/python3.6/site-packages (from pymystem3) (2.18.4)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /srv/home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (3.0.4)
> Requirement already satisfied: idna<2.7,>=2.5 in /srv/home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (2.6)
> Requirement already satisfied: urllib3<1.23,>=1.21.1 in /srv/home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (1.22)
> Requirement already satisfied: certifi>=2017.4.17 in /srv/home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (2017.7.27.1)
> Installing collected packages: pymystem3
> Successfully installed pymystem3-0.2.0
> You are using pip version 10.0.1, however version 18.0 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> 
> 
> (root) panchenko@ltgpu2$ ipython
> Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)
> Type 'copyright', 'credits' or 'license' for more information
> IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: from pymystem3 import Mystem
> 
> In [2]: text = "Красивая мама красиво мыла раму"
> 
> In [3]: m = Mystem()
>    ...: lemmas = m.lemmatize(text)
>    ...: print(''.join(lemmas))
>    ...:
> Installing mystem to /srv/home/panchenko/.local/bin/mystem from http://download.cdn.yandex.net/mystem/mystem-3.1-linux-64bit.tar.gz
> красивый мама красиво мыть рама
> ```

Windows 7

**Comment by alexanderpanchenko** [comment]
pleaset try using earlier version of pymystem3 by fixing the version number when you install it using pip - it should work for some past versions: https://pypi.org/project/pymystem3/#history

**Comment by klementev-v** [comment]
> pleaset try using earlier version of pymystem3 by fixing the version number when you install it using pip - it should work for some past versions: https://pypi.org/project/pymystem3/#history

Thanks for your responding! :)

**Comment by alexanderpanchenko** [comment]
The problem is what you most likely have 32 bit windows and Yandex does not support it in the latest Mystem versions.

**Comment by juliakarabasova** [comment]
Maybe you just don`t have the 'mystem.exe' file in that folder. If you have it in another folder write it to the mystem_bin param of Mystem().
